---
- hosts: spass_workers
  tasks:
    - name: Install apt dependencies
      become: True
      become_method: sudo
      apt: pkg={{ item }} state=installed update_cache=true
      with_items:
        - git
        - python3
        - python3-pip
        - python-setuptools
    
    - name: Download repo
      git:
          repo: 'https://github.com/Guilhermeslucas/SPaaS'
          dest: ~/repo
    - name: Installing pip dependencies
      pip:
        requirements: ~/repo/back-end/requirements.txt  
        executable: pip3
